package com.myspace.reflow_case;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LogWIH implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public LogWIH() {
    }




}